version: "3.9"

services:
  rag_chatbot:
    image: lakshkrishnasharma/rag-chatbot:v1.1
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - ./data/db:/app/data/db
      - ./data/processed:/app/data/processed
      - ./data/uploads:/app/data/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8090
    restart: unless-stopped